# Generated by Selenium IDE

import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class Run:
    def setup_method(self, method):
        self.driver = webdriver.Chrome(executable_path="./chromedriver")
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def run_policy(self):
        self.driver.get("https://www.amazon.com/")
        self.driver.set_window_size(1920, 985)
        self.driver.find_element(By.ID, "nav-search").click()
        self.driver.find_element(By.ID, "twotabsearchtextbox").click()
        self.driver.find_element(By.ID, "twotabsearchtextbox").send_keys("手機")
        self.driver.find_element(By.ID, "twotabsearchtextbox").send_keys(Keys.ENTER)
        self.driver.find_element(By.ID, "p_36/14674873011").click()
        self.driver.execute_script("window.scrollTo(0,901)")
        self.driver.execute_script("window.scrollTo(0,2014)")
        self.driver.find_element(
            By.CSS_SELECTOR, "#p_72\\/2491150011 .a-size-small"
        ).click()
        element = self.driver.find_element(
            By.CSS_SELECTOR,
            ".a-section:nth-child(5) .a-expander-header .a-spacing-none",
        )
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()


if __name__ == "__main__":
    run = Run()
    run.setup_method(run)
    run.run_policy()
